SDMProject/Models/Kidplaza.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kidplaza
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string Pattern { get; set; }
        public int Degree1 { get; set; }
        public int Degree2 { get; set; }
        public int Degree3 { get; set; }
        public int Degree4 { get; set; }
        public int Degree5 { get; set; }
        public int Degree6 { get; set; }
        public int Degree7 { get; set; }
        public int Degree8 { get; set; }
        public int Degree9 { get; set; }
        public string Cognition1 { get; set; }
        public string Cognition2 { get; set; }
        public string Cognition3 { get; set; }
        public string Cognition4 { get; set; }
        public string Cognition5 { get; set; }
        public string Cognition6 { get; set; }
        public string Decision { get; set; }
        public string Determine { get; set; }
        public string Text { get; set; }
        public string Text2 { get; set; }
        public string Text2Content { get; set; }
        public int Token { get; set; }
        public string Ans1 { get; set; }
        public string Ans2 { get; set; }
        public string Ans3 { get; set; }
        public string Ans4 { get; set; }
        public string Ans5 { get; set; }
        public string Ans6 { get; set; }
        public string Ans7 { get; set; }
        public string Ans8 { get; set; }
        public string Ans9 { get; set; }
        public string Ans10 { get; set; }
        public string Ques1 { get; set; }
        public string Ques2 { get; set; }
        public string Ques3 { get; set; }
        public string Ques4 { get; set; }
        public string Ques5 { get; set; }
        public string Ques6 { get; set; }
        public string Ques7 { get; set; }
        public string Ques8 { get; set; }
        public string Ques9 { get; set; }
        public string Ques10 { get; set; }
        public string Result { get; set; }
        public int Dr_token { get; set; }
        public int Patient_token { get; set; }
        public int checkAnsTure { get; set; }
        public int checkAnsWrong { get; set; }
    }
}

SDMProject/Controllers/KidplazasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SDMProject.Models;
using PagedList;

namespace SDMProject.Controllers
{
    [Authorize]
    public class KidplazasController : Controller
    {
        private SDMdbEntities db = new SDMdbEntities();
        private int pageSize = 10;

        public ActionResult Index(int page =1)
        {
            int currentPage = page < 1 ? 1 : page;
            var patient = from m in db.Patient
                          where m.Form == "子宮頸癌"
                          select m;


            if (Session["NameAccount"] != null)
            {
                string strAccount = Session["NameAccount"].ToString();
                int intAccount = int.Parse(strAccount);
                Login login = db.Login.Find(intAccount);

                if (!String.IsNullOrEmpty(strAccount))
                {
                    patient = patient.Where(x => x.Account == login.Account);

                    var result = from m in db.Kidplaza join
                                 n in patient on m.PatientID equals n.PatientID
                                 select m;
                    result = result.OrderBy(c => c.ID);
                    var result_kidplaza = result.ToPagedList(currentPage, pageSize);
                    return View(result_kidplaza);
                }
            }
            if (Session["NameAccount"] == null)
            {
                return RedirectToAction("Login", "Logins");
            }


            return View(db.Kidplaza.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patient.Find(id);
            TempData["kidplaza_Detail_Name"] = patient.Name;
            TempData["kidplaza_Detail_Date"] = patient.Date.ToShortDateString();
            TempData["kidplaza_Detail_pID"] = patient.DiseaseType;
            TempData["kidplaza_Detail_Age"] = patient.Age;
            TempData["kidplaza_Detail_Gender"] = patient.Gender;
            TempData["kidplaza_Detail_Form"] = patient.Form;
            TempData["kidplaza_Detail_DrName"] = patient.DrName;

            Kidplaza kidplaza = db.Kidplaza.Find(id);
            if (kidplaza == null)
            {
                return HttpNotFound();
            }
            return View(kidplaza);
        }

        public ActionResult Kidplazas_Dr_QA(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kidplaza kidplaza = db.Kidplaza.Find(id);
            TempData["Kidplazas_QA_Dr_ID"] = kidplaza.ID;
            Patient patient = db.Patient.Find(id);
            TempData["Dr_kidplaza_Detail_Name"] = patient.Name;
            TempData["Dr_kidplaza_Detail_Date"] = patient.Date.ToShortDateString();
            TempData["Dr_kidplaza_Detail_Age"] = patient.Age;
            TempData["Dr_kidplaza_Detail_Gender"] = patient.Gender;
            TempData["Dr_kidplaza_Detail_Form"] = patient.Form;
            TempData["Dr_kidplaza_Detail_DrName"] = patient.DrName;
            if (kidplaza == null)
            {
                return HttpNotFound();
            }
            return View(kidplaza);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Kidplazas_Dr_QA(FormCollection obj)
        {
            string strid = TempData["Kidplazas_QA_Dr_ID"].ToString();
            int id = int.Parse(strid);
            Kidplaza kidplaza = db.Kidplaza.Find(id);
            Patient patient = db.Patient.Find(id);
            DateTime date = DateTime.Now;
            kidplaza.Result = obj["Dr_QA_result"];

            if (kidplaza.Dr_token == 0)
                kidplaza.Dr_token = 1;
            if (kidplaza.Dr_token == 1)
            {
                kidplaza.Ans1 = obj["Dr_QA"].ToString();
                kidplaza.Dr_token++;
                patient.CheckMsg = 0;
                kidplaza.Ans6 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Index", "Patients");
            }
            if (kidplaza.Dr_token == 2)
            {
                kidplaza.Ans2 = obj["Dr_QA"].ToString();
                kidplaza.Dr_token++;
                patient.CheckMsg = 0;
                kidplaza.Ans7 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Index", "Patients");
            }
            if (kidplaza.Dr_token == 3)
            {
                kidplaza.Ans3 = obj["Dr_QA"].ToString();
                kidplaza.Dr_token++;
                patient.CheckMsg = 0;
                kidplaza.Ans8 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Index", "Patients");
            }
            if (kidplaza.Dr_token == 4)
            {
                kidplaza.Ans4 = obj["Dr_QA"].ToString();
                kidplaza.Dr_token++;
                patient.CheckMsg = 0;
                kidplaza.Ans9 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Index", "Patients");
            }
            if (kidplaza.Dr_token == 5)
            {
                kidplaza.Ans5 = obj["Dr_QA"].ToString();
                kidplaza.Dr_token = 1;
                patient.CheckMsg = 0;
                kidplaza.Ans10 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Index", "Patients");
            }
            ////db.Entry(aircut).State = EntityState.Modified;
            //db.SaveChanges();
            return View(kidplaza);
        }

        [AllowAnonymous]
        public ActionResult Kidplazas_Patient_QA(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kidplaza kidplaza = db.Kidplaza.Find(id);
            TempData["Kidplazas_QA_Patient_ID"] = kidplaza.ID;

            Patient patient = db.Patient.Find(id);
            TempData["patient_kidplaza_Detail_Name"] = patient.Name;
            TempData["patient_kidplaza_Detail_Date"] = patient.Date.ToShortDateString();
            TempData["patient_kidplaza_Detail_Age"] = patient.Age;
            TempData["patient_kidplaza_Detail_Gender"] = patient.Gender;
            TempData["patient_kidplaza_Detail_Form"] = patient.Form;
            TempData["patient_kidplaza_Detail_DrName"] = patient.DrName;
            if (kidplaza == null)
            {
                return HttpNotFound();
            }
            return View(kidplaza);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Kidplazas_Patient_QA(FormCollection obj)
        {
            string strid = TempData["Kidplazas_QA_Patient_ID"].ToString();
            int id = int.Parse(strid);
            Kidplaza kidplaza = db.Kidplaza.Find(id);
            Patient patient = db.Patient.Find(id);
            DateTime date = DateTime.Now;

            if (kidplaza.Patient_token == 1)
            {
                kidplaza.Ques1 = obj["Patient_QA"].ToString();
                kidplaza.Patient_token++;
                patient.CheckMsg = 1;
                kidplaza.Ques6 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Tmp_QA_page");
            }
            if (kidplaza.Patient_token == 2)
            {
                kidplaza.Ques2 = obj["Patient_QA"].ToString();
                kidplaza.Patient_token++;
                patient.CheckMsg = 1;
                kidplaza.Ques7 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Tmp_QA_page");
            }
            if (kidplaza.Patient_token == 3)
            {
                kidplaza.Ques3 = obj["Patient_QA"].ToString();
                kidplaza.Patient_token++;
                patient.CheckMsg = 1;
                kidplaza.Ques8 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Tmp_QA_page");
            }
            if (kidplaza.Patient_token == 4)
            {
                kidplaza.Ques4 = obj["Patient_QA"].ToString();
                kidplaza.Patient_token++;
                patient.CheckMsg = 1;
                kidplaza.Ques9 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Tmp_QA_page");
            }
            if (kidplaza.Patient_token == 5)
            {
                kidplaza.Ques5 = obj["Patient_QA"].ToString();
                kidplaza.Patient_token = 1;
                patient.CheckMsg = 1;
                kidplaza.Ques10 = date.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Tmp_QA_page");
            }
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult Tmp_QA_page()
        {
            ViewBag.Kidplazas_Tmp_QA_Msg = "問題已送出，請耐心等候醫生回復";
            return View();
        }

        [AllowAnonymous]
        public ActionResult printform(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kidplaza kidplaza = db.Kidplaza.Find(id);
            TempData["kidplazaprintform"] = kidplaza.ID;
            return View();
        }


SDMProject/Views/Kidplazas/Delete.cshtml
@model SDMProject.Models.Kidplaza

@{
    ViewBag.Title = "Delete";
}

<div>
    <h2>刪除病歷</h2>
    <hr />

    病歷號碼：
    @Html.DisplayFor(model => model.PatientID)
    <br>
    治療方法：
    @Html.DisplayFor(model => model.Pattern)
    <br>
    <br>
    @*1.接受手術治療，傷口會疼痛，復原需要時間。
    <br>
    病患答案：@Html.DisplayFor(model => model.Cognition1)
    <br>
    2.接受放射治療的效果等同手術治療，雖然沒有割除腫瘤，但陰道會乾澀且影響性生活。
    <br>
    病患答案：@Html.DisplayFor(model => model.Cognition2)
    <br>
    3.接受放射治療，卵巢亦有可能遭受輻射傷害。
    <br>
    病患答案：@Html.DisplayFor(model => model.Cognition3)
    <br>
    4.進行手術治療之後，有可能產生暫時性或慢性膀胱與腸道功能障礙。
    <br>
    病患答案：@Html.DisplayFor(model => model.Cognition4)
    <br>
    5.進行骨盆腔淋巴廓清手術之後，有可能發生淋巴水腫的副作用。
    <br>
    病患答案：@Html.DisplayFor(model => model.Cognition5)
    <br>
    6.接受放射治療，我必須分階段，經過至少 5 次的治療。
    <br>
    病患答案：@Html.DisplayFor(model => model.Cognition6)
    <br>
    7.我已經確認好想要的治療方式，我決定選擇：（下列擇一）
    <br>
    病患答案：@Html.DisplayFor(model => model.Decision)
    <br>
    8.我目前還無法決定
    <br>
    病患答案：@Html.DisplayFor(model => model.Determine)
    @Html.DisplayFor(model => model.Text)
    @Html.DisplayFor(model => model.Text2)
    <br>
    <br>*@

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="刪除" class="btn btn-outline-primary" />
            <span class="btn btn-outline-primary">@Html.ActionLink("返回清單", "Index","Patients")</span>
        </div>
    }
</div>

SDMProject/Views/Kidplazas/Tmp_QA_page.cshtml
@{
    Layout = "~/Views/Shared/_NoLayoutPage.cshtml";
}

<html>
<head>
    <title>Aircut_dr_QA</title>
</head>
<body>
    <h2 style="text-align:center;">@ViewBag.Kidplazas_Tmp_QA_Msg</h2>
</body>
</html>

SDMProject/Views/Kidplazas/check_ID.cshtml
@{
    Layout = "~/Views/Shared/_NoLayoutPage.cshtml";
}

<!DOCTYPE html>

<form action="/Kidplazas/check_ID" align="center" valign="center" method="post">
    @Html.AntiForgeryToken()
    <h1>請輸入身分證字號</h1>
    <br>
    <input type="text" name="Check">
    <input type="submit" value="登入" class="btn btn-outline-primary" />
</form>

<br><br>
<h2 style="text-align:center;font-weight:bold;">@ViewBag.ck4Msg</h2>

SDMProject/Views/Kidplazas/printform.cshtml
@model SDMProject.Models.Kidplaza

@{
    ViewBag.title = "printform";
}
@{
    Layout = "~/Views/Shared/_NoLayoutPage.cshtml";
}

<html>
<head>
    <style>
        body {
            background-color: #FFFFFF;
            font-family: sans-serif;
            line-height: 1.6;
        }

        th, td {
            padding: 8px;
        }

        #table {
            border: 1px solid #000;
            border-collapse: collapse;
            width: 100%;
        }

        #th01 {
            text-align: center;
        }

        #c02 {
            font-weight: bolder;
            text-align: center;
            display: block;
        }

        #c03 {
            font-weight: bolder;
        }

        #boxtext01 {
            border: 1px black solid;
            padding: 6px;
            width: auto;
            border-radius: 10px;
            font-weight: bolder;
            text-align: center;
        }

        img {
            /*width: auto;*/
            height: auto;
            max-width: 100%;
            max-height: 100%;
        }
    </style>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no" />
    <script type="text/javascript" src="//cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="//static.runoob.com/assets/qrcode/qrcode.min.js"></script>

</head>

<body>
    <br />
    <h1 id="c03" style="text-align:center;">
        我有子宮頸癌，有什麼治療選擇？
        <br />
        該選擇手術治療或是放射治療呢？
    </h1>
    <br /><br />

    &emsp;&emsp;當醫師藉由子宮頸抹片、切片證實您罹患子宮頸癌，並經由影像學診斷分期為 IB（第 1 期末）至 IIA（第 2 期初）之間時，代表您現在需要思考下一步的治療手段，該選擇手術治療或是放射治療。本表單將協助您瞭解病因及有哪些治療選擇，請跟著我們的步驟，一步步探索自己的需求及在意的事情，希望能幫助您思考適合自己後續的治療計畫。
    <br /><br />
    ● <span id="c03">適用對象：</span><br />
    &emsp;✓ 年滿 20 歲<br />
    &emsp;✓ 罹患子宮頸癌<br />
    &emsp;✓ 疾病期別介於 IB 到 IIA<br /><br />

    ● <span id="c03">疾病簡介：</span><br /><br />
    <img src="~/img/img01.png" style="display:block; margin:auto;" />&emsp;
    <img src="~/img/img02.png" style="display:block; margin:auto;" /><br /><br />

    ● <span id="c03">治療選項簡介：</span><br />
    &emsp;✦ 手術治療：早期子宮頸癌的標準治療是手術療法，臨床分期 IIA 之前的子宮頸癌，通常會進行根除性子宮切除手術，以及骨盆淋巴廓清手術。另外對 IB 期之前，腫瘤體積小於 2 公分的子宮頸癌，又想保留生育能力的婦女，可考慮子宮頸切除手術（或合併骨盆腔淋巴清除手術）。<br /><br />
    &emsp;✦ 放射線治療：研究顯示對於腫瘤分期 IB-IIA 的子宮頸癌，放射治療也可以達到跟手術治療相同的效果。在接受放射治療前，會先進行治療前的定位準備，一至二周內會開始進行放射治療，需進行 5 次以上的放射治療。<br /><br />
    &emsp;✦ 熱治療：熱能夠造成腫瘤細胞暫時性的生長停滯，有效增加放射治療的效果，因此在較大的腫瘤（&gt; 4 cm）以上可以考慮配合化放射治療療程同步加上熱治療。<br /><br />

    ● <span id="c03">您目前比較想要選擇的方式是：</span><br />
    <input type="checkbox" />手術治療
    <input type="checkbox" />放射治療±熱療
    <input type="checkbox" />目前還不清楚<br /><br />

    ● <span id="c03">接著請透過以下四個步驟來幫助您做決定</span><br /><br />

    <div id="boxtext01">步驟一、選項間的比較</div>
    <br />

    <table border=1 align=center>
        <tr align=center>
            <th rowspan=2 width="100px">考量\選項</th>
            <th rowspan=2 width="400px">手術治療</th>
            <th colspan=2 width="400px">放射治療</th>
        </tr>
        <tr align=center>
            <td width="350px">放射治療</td>
            <td width="350px">加上熱治療</td>
        </tr>
        <tr>
            <th id="th01">20年存活率</th>
            <td align=center>100人中有 72 個人治療後會存活超過 20 年</td>
            <td colspan=2 align=center>100人中有 77 個人治療後會存活超過 20 年</td>
        </tr>
        <tr>
            <th id="th01">復發率</th>
            <td align=center>100人中有 28 個人治療後會復發</td>
            <td colspan=2 align=center>100人中有 27 個人治療後會復發</td>
        </tr>
        <tr>
            <th id="th01">優點</th>
            <td>
                1.手術為一次性治療。
                <br />
                2.卵巢可以選擇性保留。
                <br />
                3.傳統手術治療全程健保給付。
                <br />
            </td>
            <td>
                1.沒有手術傷口。
                <br />
                2.可以搭配熱治療療程，同時進行。
                <br />
                3.放射治療全程健保給付。
            </td>
            <td>
                1.沒有手術傷口。
                <br />
                2.可以搭配放射治療，同時進行。
                <br />
                3.增加放射治療之療效。
            </td>
        </tr>

        <tr>
            <th id="th01">缺點/風險/副作用</th>
            <td>
                1.傷口疼痛。
                <br />
                2.傷口有可能會感染。
                <br />
                3.恢期較長。
                <br />
                4.膀胱與腸道功能障礙。
                <br />
                5.淋巴水腫。
                <br />
                6.需住院進行治療。
                <br />
            </td>
            <td>
                1.主要腫瘤仍殘存體內。
                <br />
                2.卵巢及附近器官輻射傷害作用較大。
                <br />
                3.黏膜出血。
                <br />
                4.腸粘黏/腸阻塞。
                <br />
                5.陰道乾澀，影響性生活。
                <br />
                6.放射治療需治療 5 次以上。
            </td>
            <td>
                1.需與放射治療同步進行，缺點/風險/副作用與放射治療同。
                <br />
                2.體內植入金屬或安裝節律器的病人無法進行熱治療，以免燙傷。
                <br />
                3.可能會有脂肪結塊的情形。
                <br />
                4.需自費進行療程。
            </td>
        </tr>
    </table>

    <br /><br />
    <div id="boxtext01">步驟二、您在意的項目是什麼？以及在意的程度？</div>
    <br />

    <table border=1 align=center>
        <tr align=center>
            <th rowspan=2>考量項目</th>
            <th colspan=6>在意程度</th>
        </tr>
        <tr align=center>
            <th colspan=6>完全不在意 → 非常在意</th>
        </tr>
        <tr align=center>
            <th>疼痛</th>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr align=center>
            <th>擔心體內殘存大體積腫瘤</th>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr align=center>
            <th>影響卵巢賀爾蒙功能</th>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr align=center>
            <th>影響生育功能</th>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr align=center>
            <th>影響性生活</th>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr align=center>
            <th>擔心輻射後遺症</th>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr align=center>
            <th>擔心手術後遺症</th>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr align=center>
            <th>擔心療程需多次治療</th>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr align=center>
            <th>其它</th>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
    </table>

    <br /><br />
    <div id="boxtext01">步驟三、對於以上提供的資訊，您是否已經了解呢？</div>
    <br />

    <span id="c03">1.接受手術治療，傷口會疼痛，復原需要時間。</span><br />
    <input type="checkbox" />對
    <input type="checkbox" />不對
    <input type="checkbox" />不確定<br /><br />

    <span id="c03">2.接受放射治療的效果等同手術治療，雖然沒有割除腫瘤，但陰道會乾澀且影響性生活。</span><br />
    <input type="checkbox" />對
    <input type="checkbox" />不對
    <input type="checkbox" />不確定<br /><br />

    <span id="c03">3.接受放射治療，卵巢亦有可能遭受輻射傷害。</span><br />
    <input type="checkbox" />對
    <input type="checkbox" />不對
    <input type="checkbox" />不確定<br /><br />

    <span id="c03">4.進行手術治療之後，有可能產生暫時性或慢性膀胱與腸道功能障礙。</span><br />
    <input type="checkbox" />對
    <input type="checkbox" />不對
    <input type="checkbox" />不確定<br /><br />

    <span id="c03">5.進行骨盆腔淋巴廓清手術之後，有可能發生淋巴水腫的副作用。</span><br />
    <input type="checkbox" />對
    <input type="checkbox" />不對
    <input type="checkbox" />不確定<br /><br />

    <span id="c03">6.接受放射治療，我必須分階段，經過至少 5 次的治療。</span><br />
    <input type="checkbox" />對
    <input type="checkbox" />不對
    <input type="checkbox" />不確定<br /><br />

    <div id="boxtext01">步驟四、您現在確認好醫療方式了嗎？</div>
    <br />

    <span id="c03">7.我已經確認好想要的治療方式，我決定選擇：（下列擇一）</span><br />
    <input type="checkbox" />手術治療
    <input type="checkbox" />放射治療±熱療
    <input type="checkbox" />目前還不清楚<br /><br />

    <span id="c03">8.我目前還無法決定</span><br />
    <input type="checkbox" />我想要再與我的主治醫師討論我的決定。<br />
    <input type="checkbox" />我想要再與其他人（包含配偶、家人、朋友或第二意見提供者…）討論我的決定。<br />
    <input type="checkbox" />對於以上治療方式，我想要再瞭解更多，我的問題有：<br />
    <textarea cols="100" rows="4"></textarea><br />
    <input type="checkbox" />不進行任何治療，原因：<br />
    <textarea cols="100" rows="4"></textarea><br /><br />

    <span id="c02">完成以上評估後，您可以列印及攜帶此份結果與您的主治醫師討論。</span><br />

    @{
        string str = TempData["kidplazaprintform"].ToString();
    }

    <div style="visibility:hidden">
        @*<input id="text" type="text" value=" @Url.Action("KidplazasForm", "Kidplazas", new { id = str }, "http") "  />*@
        <input id="text" type="text" value=" @Url.Action("check_ID", "Kidplazas", new { id = str }, "http")" />
    </div>

    <div id="qrcode"></div>

    <script type="text/javascript">
        var qrcode = new QRCode(document.getElementById("qrcode"), {
            width: 120,
            height: 120
        });

        function makeCode() {
            var elText = document.getElementById("text");
            if (!elText.value) {
                alert("Input a text");
                elText.focus();
                return;
            }
            qrcode.makeCode(elText.value);
        }
        makeCode();
        $("#text").
            on("blur", function () {
                makeCode();
            }).
            on("keydown", function (e) {
                if (e.keyCode == 13) {
                    makeCode();
                }
            });
    </script>
</body>
</html>